### ISSUE TITLE
Pushover

### ISSUE THREAD

**Issue by fetsus69** [ottonet/19626_Pushover#1]
Hi,

I try to use the Pushover Funktion in my HomeServer 4. I already imported the .hsl into my HS and filled out the inputs. I created a Testbutton to send a 14byte Text (Pushover Message) "Test" but the Message was not sent.
![pushover](https://cloud.githubusercontent.com/assets/19716252/15777698/aecaf192-2991-11e6-907b-19adf209c80a.JPG)

Can anybody help me to get my Message (;-))

**Comment by rvencu** [comment]
Well, in the readme it says the priority 2 is not supported. Try changing that to 1.

Also make sure the HS has internet access (proper gateway, dns servers). I also setup Internet access option as dedicated line.

Just configured it today with Experte 4.5 and it worked after a little networking troubleshooting.
