### ISSUE TITLE
Certificate verify error with Gira Experte 4.7

### ISSUE THREAD

**Issue by alexaecho** [ottonet/19626_Pushover#2]
Since upgrading to Gira Experte 4.7 this logic is not working any more.
The home server debug page shows the following exception:

`15.08.2018 21:11:16 (1)
File "./../hssrc/hs_logik.py", line 232, in calc
File "formula", line 1, in [module]
File "[19626_Pushover]", line 45, in sendmsg
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 431, in open
response = self._open(req, data)
File "/usr/lib/python2.7/urllib2.py", line 449, in _open
'_open', req)
File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
context=self._context)
File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
raise URLError(err)
URLError: [urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)]
[5012L, 19626L, 0L, 'EC[2] and len(EN[2])]0', 'SN[1].sendmsg(EN[2], EN[3], EN[4], EN[5], EN[6], EN[7], EN[8], EN[9], EN[10], EN[11])', '', 0L, 0L, 0L, 0L]`

Could that be fixed?

**Comment by shivan** [comment]
Mhm I think this could be of the switch from Python 2.6 to 2.7. In 2.7 it verifies SSL certificates by default.
And maybe the needed certificate is not in the store of python.

Intermediate solution could be, using:

    ssl._create_default_https_context = ssl._create_unverified_context

I think that line could be added at line 220 and then tested again.

I was unable to update yet, because I wait for the compatible android app before updating to 4.7.

https://access.redhat.com/articles/2039753

I changed it in the attached file, but not tested:
[19626_Pushover_V0.91.zip](https://github.com/ottonet/19626_Pushover/files/2291457/19626_Pushover_V0.91.zip)

**Comment by alexaecho** [comment]
Thank you for your quick response and your time to look into that.
I updated to 0.91 but now I get the following exceptions at startup of the HS4:

15.08.2018 21:49:20 (1)File "./../hssrc/hs_logik.py", line 232, in calcFile "formula", line 1, in [module]File "[19626_Pushover]", line 17ssl._create_default_https_context = ssl._create_unverified_context^IndentationError: unexpected indent[5012L, 19626L, 0L, 'EI', "eval(compile(__import__('base64').decodestring('CmlmIEVJID09IDE6CiAgICBnbG9iYWwgc29ja2V0CiAgICBpbXBvcnQgc29ja2V0CiAgICBpZiBub3QgaGFzYXR0cihzb2NrZXQsIl9oc19kbnNyZXNvbHZlciIpOgogICAgICAgIHNvY2tldC5fc29ja2V0X2dldGFkZHJpbmZvID0gc29ja2V0LmdldGFkZHJpbmZvCiAgICAgICAgc29ja2V0Ll9oc19kbnNyZXNvbHZlciA9IHNlbGYuTUMuRE5TUmVzb2x2ZXIuZ2V0SG9zdElQCiAgICAgICAgZGVmIF9oc2dldGFkZHJpbmZvKGhvc3QsIHBvcnQsIGZhbWlseT0wLCBzb2NrdHlwZT0wLCBwcm90bz0wLCBmbGFncz0wKToKICAgICAgICAgICAgcmV0dXJuIHNvY2tldC5fc29ja2V0X2dldGFkZHJpbmZvKHNvY2tldC5faHNfZG5zcmVzb2x2ZXIoaG9zdCkscG9ydCwgZmFtaWx5LHNvY2t0eXBlLHByb3RvLGZsYWdzKQogICAgICAgIHNvY2tldC5nZXRhZGRyaW5mbyA9IF9oc2dldGFkZHJpbmZvCiAgICBjbGFzcyBwdXNob3Zlcl9tZXNzYWdlKG9iamVjdCk6CiAgICAgICAgZGVmIF9faW5pdF9fKHNlbGYsIHVybCk6CiAgICAgICAgICAgIHNlbGYudXJsID0gdXJsCiAgICAgICAgICAgIHByaW50IHVybAogICAgICAgIGRlZiBzZW5kbXNnKHNlbGYsIF9tZXNzYWdlLCBfdG9rZW4sIF91c2VyLCBfZGV2aWNlLCBfdGl0bGUsIF91cmwsIF91cmx0aXRsZSwgX3ByaW9yaXR5LCBfdGltZXN0YW1wLCBfc291bmQpOgogICAgICAgICAgICBpbXBvcnQgdXJsbGliLHVybGxpYjIKCQkJc3NsLl9jcmVhdGVfZGVmYXVsdF9odHRwc19jb250ZXh0ID0gc3NsLl9jcmVhdGVfdW52ZXJpZmllZF9jb250ZXh0CiAgICAgICAgICAgIG1zZyA9IHt9CiAgICAgICAgICAgIGlmIF9tZXNzYWdlOgogICAgICAgICAgICAgICAgbXNnLnVwZGF0ZSh7J21lc3NhZ2UnOiBfbWVzc2FnZX0pCiAgICAgICAgICAgIGlmIF90b2tlbjoKICAgICAgICAgICAgICAgIG1zZy51cGRhdGUoeyd0b2tlbic6IF90b2tlbn0pCiAgICAgICAgICAgIGlmIF91c2VyOgogICAgICAgICAgICAgICAgbXNnLnVwZGF0ZSh7J3VzZXInOiBfdXNlcn0pCiAgICAgICAgICAgIGlmIF9kZXZpY2U6CiAgICAgICAgICAgICAgICBtc2cudXBkYXRlKHsnZGV2aWNlJzogX2RldmljZX0pCiAgICAgICAgICAgIGlmIF90aXRsZToKICAgICAgICAgICAgICAgIG1zZy51cGRhdGUoeyd0aXRsZSc6IF90aXRsZX0pCiAgICAgICAgICAgIGlmIF91cmw6CiAgICAgICAgICAgICAgICBtc2cudXBkYXRlKHsndXJsJzogX3VybH0pCiAgICAgICAgICAgIGlmIF91cmx0aXRsZToKICAgICAgICAgICAgICAgIG1zZy51cGRhdGUoeyd1cmxfdGl0bGUnOiBfdXJsdGl0bGV9KQogICAgICAgICAgICBpZiBfcHJpb3JpdHk6CiAgICAgICAgICAgICAgICBtc2cudXBkYXRlKHsncHJpb3JpdHknOiBpbnQoX3ByaW9yaXR5KX0pCiAgICAgICAgICAgIGlmIF90aW1lc3RhbXA6CiAgICAgICAgICAgICAgICBtc2cudXBkYXRlKHsndGltZXN0YW1wJzogaW50KF90aW1lc3RhbXApfSkKICAgICAgICAgICAgaWYgX3NvdW5kOgogICAgICAgICAgICAgICAgbXNnLnVwZGF0ZSh7J3NvdW5kJzogX3NvdW5kfSkKICAgICAgICAgICAgcHJpbnQgbXNnCiAgICAgICAgICAgIHJlcSA9IHVybGxpYjIuUmVxdWVzdChzZWxmLnVybCwKICAgICAgICAgICAgICAgIGhlYWRlcnMgPSB7CiAgICAgICAgICAgICAgICAgICAgIkNvbnRlbnQtVHlwZSI6ICJhcHBsaWNhdGlvbi94LXd3dy1mb3JtLXVybGVuY29kZWQiLAogICAgICAgICAgICAgICAgICAgICJBY2NlcHQiOiAiKi8qIiwKICAgICAgICAgICAgICAgICAgICAiVXNlci1BZ2VudCI6ICdHaXJhIEhvbWVTZXJ2ZXIgUHVzaG92ZXIgKDE5NjI2KSBWZXIuIFYwLjkxJywKICAgICAgICAgICAgICAgIH0sIGRhdGEgPSB1cmxsaWIudXJsZW5jb2RlKG1zZykpCiAgICAgICAgICAgIHJlc3BvbnNlID0gdXJsbGliMi51cmxvcGVuKHJlcSkK'),'[19626_Pushover]','exec'))", '', 0L, 0L, 0L, 0L]
--
15.08.2018 21:49:20 (1)File "./../hssrc/hs_logik.py", line 232, in calcFile "formula", line 1, in [module]NameError: name 'pushover_message' is not defined[5012L, 19626L, 1L, 'EI', 'pushover_message(EN[1])', '', 0L, 0L, 1L, 0L]

**Comment by shivan** [comment]
yes... bad indentation... tab instead of blanks ... my fault. Editor uses tabs by default, but this file is with spaces.
[19626_Pushover_V0.91.hsl.zip](https://github.com/ottonet/19626_Pushover/files/2291519/19626_Pushover_V0.91.hsl.zip)

**Comment by alexaecho** [comment]
Ok, I think we are getting closer ;-)

Remaining exception:
15.08.2018 22:22:02 (2)
File "./../hssrc/hs_logik.py", line 232, in calc
File "formula", line 1, in [module]
File "[19626_Pushover]", line 17, in sendmsg
NameError: global name 'ssl' is not defined
[5012L, 19626L, 0L, 'EC[2] and len(EN[2])]0', 'SN[1].sendmsg(EN[2], EN[3], EN[4], EN[5], EN[6], EN[7], EN[8], EN[9], EN[10], EN[11])', '', 0L, 0L, 0L, 0L]

**Comment by shivan** [comment]
Now it WILL work, because I tried it with the emulator... :)
[19626_Pushover_V0.91.hsl.zip](https://github.com/ottonet/19626_Pushover/files/2294999/19626_Pushover_V0.91.hsl.zip)

Funny is, it is not working with python 2.6 (aka Gira Experte 4.5) it is only working with Python 2.7 (aka will be Gira Experte 4.7)

**Comment by alexaecho** [comment]
Bingo. Now it works. 

Thank you very much for your support. I really appreciate that.
